---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy
  labels:
    app: tinyproxy
spec:
  selector:
    matchLabels:
      app: tinyproxy
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      containers:
      - name: tinyproxy
        image: dannydirect/tinyproxy:latest
        ports:
        - containerPort: 8888
          hostPort: 8888
        args: ["ANY"]
